version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: node index.js
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - ./database-file:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20